DELETE http://localhost:8080/events/1/register HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzU2MTQ0NzUyLCJ1c2VySWQiOjJ9.mU8x6x9MWNhoaK3n0mWLb9wZDQIv8-B-HcJ6aQHVrnA
