version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - revive  # replaces golint
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  revive:
    min-confidence: 0.8
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true  # Allow packages without comments
      - name: var-naming
        disabled: true  # Disable var-naming rule that flags "utils" as meaningless

issues:
  exclude-rules:
    # Exclude stuttering warnings for gRPC server types
    - path: grpc/
      linters:
        - revive
      text: "stutters"
    # Exclude all revive warnings from utils directory (package naming convention)
    - path: utils/
      linters:
        - revive
  # Exclude generated protobuf files
  exclude-files:
    - ".*\\.pb\\.go$"